# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  國立雲林科技大學化學工程與材料工程系/所/博士班
email: m85091081@gmail.com
description: 國立雲林科技大學化學工程與材料工程系/所/博士班 # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.che.yuntech.edu.tw/" # the base hostname & protocol for your site
gems: [jekyll-paginate]
paginate: 20
paginate_path: "/page:num/"
# Build settings
markdown: kramdown
